### ISSUE TITLE
ImportError: No module named packages.urllib3.poolmanager

### ISSUE THREAD

**Issue by cbun** [kbase/assembly#311]
Have you guys run into this?  Seems related to `requests_toolkit`.

Running on Ubuntu 14.04

```
$ ./arastd.py -c arast.conf
Traceback (most recent call last):
  File "./arastd.py", line 18, in <module>
    import router
  File "/mnt/arast/assembly/lib/assembly/router.py", line 29, in <module>
    import asmtypes
  File "/mnt/arast/assembly/lib/assembly/asmtypes.py", line 5, in <module>
    import client
  File "/mnt/arast/assembly/lib/assembly/client.py", line 19, in <module>
    from shock import Shock
  File "/mnt/arast/assembly/lib/assembly/shock.py", line 9, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/ssl.py", line 13, in <module>
    from requests.packages.urllib3.poolmanager import PoolManager
ImportError: No module named packages.urllib3.poolmanager
```

https://github.com/sigmavirus24/requests-toolbelt/issues/82

**Comment by sigmavirus24** [comment]
You almost certainly installed requests with you distro's package manager. That's the root cause of this. They break requests' API and so libraries that build on top of requests (and that API) break.
